version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
    - echo "Entered pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean install
  post_build:
    commands:
    - echo "Entered the post-build phase"
artifacts:
  files:
    - tartget/devhub-developers-social-0.0.1-SNAPSHOT.jar